### ISSUE TITLE
Error on import Module

### ISSUE THREAD

**Issue by cheater001** [ng2-ui/ng2-sticky#2]
`Uncaught Error: Unexpected value 'Ng2StickyModule' imported by the module 'AppModule'.`

Using this angular [seed](https://github.com/AngularClass/angular2-webpack-starter) for my app

**Comment by allenhwkim** [comment]
Did you do `npm install ng2-sticky --save` ?

**Comment by cheater001** [comment]
ok im sorry its alright.
