### ISSUE TITLE
ng2-utils dependency

### ISSUE THREAD

**Issue by cheater001** [ng2-ui/ng2-sticky#3]
Please move ng2-utils from 'devDependencies' to 'dependencies'. You can read [devDependencies](https://docs.npmjs.com/files/package.json#devdependencies). In other words ng2-utils fail to install in my project node_modules.

**Comment by allenhwkim** [comment]
I think if you use `ng2-sticky.umd.js`, all these dependencies, which are internally used by `ng2-sticky`, because all are already inside `.umd.js`. Thus, it is not necessary to be installed into your module.

I might haven't thought of some other situation. What am I missing?

**Comment by xealot** [comment]
While that might be true, you should distribute a project that works without the use of pre-bundled files.

**Comment by allenhwkim** [comment]
K, I will add `ng2-utils` as dependencies from devDependencies.
